version: '3.4'

volumes:
  json-data: # suricata json input
  rules-data: # scirius rules
  clamav-data: # clamav rules
  clamav-log: # clamav log

services:

  suricata:
    image: tatsui/suricata
    build: ./suricata
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - ./pcap:/pcap
      - ./suricata/config/suricata.yaml:/etc/suricata/suricata.yaml:ro
      - ./suricata/rules/suricata.rules:/etc/suricata/rules/suricata.rules:ro
      - json-data:/var/log/suricata/
      - rules-data:/etc/suricata/rules/
    #command: bash -c "suricata -c /etc/suricata/suricata.yaml -i enp0s25"

  yara-gen:
    image: tatsui/yara-gen
    build: yara-gen
    volumes:
       - ./malware:/malware

  yara:
    image: tatsui/yara
    build: yara
    volumes:
       - ./extract_files:/malware:ro
       - ./yara/rules:/rules


  # antivirus software
  clamav:
    image: tatsui/clamav
    build: ./antivirus/clamav
    volumes:
       - ./extract_files:/malware:ro
       - clamav-data:/usr/local/share/clamav
       - clamav-log:/var/log/clamav

  sophos:
    image: tatsui/sophos
    build: ./antivirus/sophos
    volumes:
       - ./extract_files:/malware:ro

  escan:
    image: tatsui/escan
    build: ./antivirus/escan
    volumes:
       - ./extract_files:/malware:ro
  avg:
    image: tatsui/avg
    build: ./antivirus/avg
    volumes:
       - ./extract_files:/malware:ro

  avast:
    image: tatsui/avast
    build: ./antivirus/avast
    volumes:
       - ./extract_files:/malware:ro

  comodo:
    image: tatsui/comodo
    build: ./antivirus/comodo
    volumes:
       - ./extract_files:/malware:ro


  fsecure:
    image: tatsui/fsecure
    build: ./antivirus/fsecure
    volumes:
       - ./extract_files:/malware:ro

  fport:
    image: tatsui/fport
    build: ./antivirus/fport
    volumes:
       - ./extract_files:/malware:ro


  windows-defender:
    image: tatsui/windows-defender
    build: ./antivirus/windows-defender
    volumes:
       - ./extract_files:/malware:ro
